caesb.username=karlabrito
caesb.password=Caesb@693
caesb.execucao.somente-uma-os=true

caesb.os.rpp=250

# Email notification settings (Twilio SendGrid)
email.sendgrid.api-key=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
email.from=desenvolvimento@msconsultoriati.com
email.from-name=Automacao Bot OS - 250
email.to=desenvolvimento@msconsultoriati.com
email.enabled=true

# Múltiplos destinatários (opcional - use ao invés de email.to ou em conjunto)
email.recipients[0]=quesnei.cavalcante@gmail.com
email.recipients[1]=gestaocontazul@polemicaconstrutora.com.br
email.recipients[2]=bcezar@outlook.com
email.recipients[3]=maike.silva@msconsultoriati.com